#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------
# This image includes glibc. Change to FROM alpine:3.10 if you don't need glibc.
FROM frolvlad/alpine-glibc:alpine-3.10 

# Install dependencies, git, and bash
RUN apk add --no-cache libstdc++ libgcc git bash 
