version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick a version of PHP version: 8, 8.1, 8.0, 7, 7.4
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "8.1-bullseye"
        # Optional Node.js version
        NODE_VERSION: "none"


    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    ports:
    - "1433:1433"
    volumes:
    - mssql_volume:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: A_STR0NG_Passw0rd!

volumes:
  mssql_volume:
