# Update the VARIANT arg in devcontainer.json to pick an Debian version: buster (or debian-10), stretch (or debian-9)
ARG VARIANT=buster
FROM mcr.microsoft.com/vscode/devcontainers/cpp:${VARIANT}

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update \
#     && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
