# [Choice] Debian OS version (use bullseye or bullseye-slim on local arm64/Apple Silicon): buster, buster-slim, bullseye, bullseye-slim
ARG VARIANT="bullseye-slim"
FROM mcr.microsoft.com/vscode/devcontainers/rust:1-${VARIANT}

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
