name: 'VSCDC smoke test'
inputs:
  definition:
    description: 'Definition to test'
    required: true
    default: 'debian'
  image:
    description: 'Image to run smoke test in'
    required: true
    default: 'none'
  user:
    description: 'User in container image to use for smoke test'
    required: true
    default: 'vscode'

runs:
  using: composite
  steps:
    - name: Checkout main
      id: checkout_release
      uses: actions/checkout@v2
      with:
        repository: 'microsoft/vscode-dev-containers'
        path: '__build'
        ref: 'main'

    - name: Build image
      id: build_image
      shell: bash
      run: |
        set -e

        # Symlink build scripts from main to improve security when testing PRs
        if [ -d "$GITHUB_WORKSPACE/__build/build" ]; then
          cd "$GITHUB_WORKSPACE/__build"
          yarn install
          cd "$GITHUB_WORKSPACE"
          rm -rf build node_modules
          ln -s "$GITHUB_WORKSPACE/__build/build" build
          ln -s "$GITHUB_WORKSPACE/__build/node_modules" node_modules
        else
          echo "WARNING: Using build/vscdc from ${{ github.ref }} instead of main."
          yarn install
        fi

        # Run test build
        chmod +x build/vscdc
        build/vscdc push  ${{ inputs.definition }} \
                          --no-push \
                          --release dev \
                          --github-repo "microsoft/vscode-dev-containers" \
                          --registry "mcr.microsoft.com" \
                          --registry-path "vscode/devcontainers" \
                          --stub-registry "mcr.microsoft.com" \
                          --stub-registry-path "vscode/devcontainers"

    - name: Test image
      id: test_image
      shell: bash
      run: |
        # Run test script for image if one exists

        if [ "${{ inputs.image }}" = "none" ]; then
          echo "Image not specified. Aborting test."
          exit 0
        fi

        set -e

        # Update UID/GID for user in container - Actions uses different UID/GID than container
        # which causes bind mounts to be read only and cause certain write tests to fail
        # The dev container CLI handles this automatically but we're not using it.
        local_uid=$(id -u)
        local_gid=$(id -g)
        echo "(*) Updating container user UID/GID..."
        echo -e "FROM ${{ inputs.image }}\n \
          RUN export sudo_cmd="" \
            && if [ "$(id -u)" != "0" ]; then export sudo_cmd=sudo; fi \
            && \${sudo_cmd} groupmod -g ${local_gid} ${{ inputs.user }} \
            && \${sudo_cmd} usermod -u ${local_uid} -g ${local_gid} ${{ inputs.user }}" > uid.Dockerfile
        cat uid.Dockerfile
        docker buildx build --load -t ${{ inputs.image }}-uid -f uid.Dockerfile .

        # Start container
        echo "(*) Starting container..."
        container_name="vscdc-test-container"
        docker run -d --name ${container_name} --rm --init --privileged -v "$(pwd)/containers/${{ inputs.definition }}:/workspace" ${{ inputs.image }}-uid /bin/sh -c 'while sleep 1000; do :; done'

        # Fake out existence of extensions, VS Code Server
        echo "(*) Stubbing out extensions and VS Code Server..."
        dev_container_relative_path="containers/${{ inputs.definition }}/.devcontainer"
        mkdir -p "/tmp/${dev_container_relative_path}"
        cp -f "$(pwd)/${dev_container_relative_path}/devcontainer.json" "/tmp/${dev_container_relative_path}/"
        dev_container_tmp="/tmp/${dev_container_relative_path}/devcontainer.json"
        sed -i'.bak' -e "s/\\/\\/.*/ /g" "${dev_container_tmp}"
        extensions="$(jq '.extensions' --compact-output "${dev_container_tmp}" | tr -d '[' | tr -d ']' | tr ',' '\n' 2>/dev/null || echo -n '')"
        docker exec -u "${{ inputs.user }}" ${container_name} /bin/sh -c "\
          mkdir -p \$HOME/.vscode-server/bin \$HOME/.vscode-server/extensions \
          && cd \$HOME/.vscode-server/extensions \
          && if [ \"${extensions}\" != '' ]; then echo \"${extensions}\" | xargs -n 1 mkdir -p; fi \
          && find \$HOME/.vscode-server/ -type d"

        # Run actual test
        echo "(*) Running test..."
        docker exec -u "${{ inputs.user }}" ${container_name} /bin/sh -c  '\
          set -e \
          && cd /workspace \
          && if [ -f "test-project/test.sh" ]; then \
            cd test-project \
            && if [ "$(id -u)" = "0" ]; then \
              chmod +x test.sh; \
            else \
              sudo chmod +x test.sh; \
            fi \
            && ./test.sh; \
          else \
            ls -a; 
          fi'