# Hit Alt-D preview me!
@startuml
title First Diagram
legend
    VS Code can do that?
end legend
VisualStudioCode -> Agent: openFolder(path)
Agent -> ExtensionHost: installExtensions
ExtensionHost -> ExtensionHost: download
ExtensionHost -> ExtensionHost: install
ExtensionHost -> Agent: return true
Agent -> VisualStudioCode: return true
@enduml

@startuml
title Second Diagram
legend
    VS Code can do that?
end legend
VisualStudioCode -> Agent: installWorkspaceExtension(id)
Agent -> ExtensionHost: installExtension(id)
ExtensionHost -> ExtensionHost: download
ExtensionHost -> ExtensionHost: install
ExtensionHost -> Agent: return true
Agent -> VisualStudioCode: return true
@enduml