# Update the VARIANT arg in devcontainer.json to pick an Alpine version: 3.10, 3.11, 3.12
ARG VARIANT=3.12
FROM mcr.microsoft.com/vscode/devcontainers/base:alpine-${VARIANT}

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apk update \
#     && apk add --no-cache <your-package-list-here>
