# [Choice] Alpine version: 3.12, 3.11, 3.10
ARG VARIANT=3.12
FROM mcr.microsoft.com/vscode/devcontainers/base:alpine-${VARIANT}

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apk update \
#     && apk add --no-cache <your-package-list-here>
