#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

# ImageURL: https://github.com/Azure/azure-functions-docker/blob/master/host/3.0/buster/amd64/java/java8-core-tools.Dockerfile
FROM mcr.microsoft.com/azure-functions/java:3.0-java8-core-tools
