FROM mcr.microsoft.com/vscode/devcontainers/base:alpine
WORKDIR /src

# [Optional] Uncomment this section to install additional OS packages you may want.
#
# RUN apk add --no-cache <your-package-list-here>
