# Find the Dockerfile for mcr.microsoft.com/azure-functions/node:3.0-node10-core-tools at this URL
# https://github.com/Azure/azure-functions-docker/blob/master/host/3.0/buster/amd64/node/node10/node10-core-tools.Dockerfile
FROM mcr.microsoft.com/azure-functions/node:3.0-node10-core-tools
