name: 'Deploy Devcontainer Features'
on:
  push:
    tags:
    - 'v*'

jobs:
  deploy: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get tag name
        id: get_tag_name  
        run: echo "::set-output name=tag::$(echo "${{ github.ref }}" | grep -oP 'refs/tags/\K(.+)')"
        
      - name: Copy scripts to src folder
        id: copy_scripts
        run: cp -r ./script-library/*.sh ./script-library/container-features/src
          
      - name: Publish Dev container features
        uses: microsoft/publish-dev-container-features-action@main
        with:
          path-to-features: './script-library/container-features/src'
          
      - name: Get or Create Release at current tag
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Lets us upload our own artifact from previous step
          artifactErrorsFailBuild: true
          artifacts: './features.tgz'
          token: ${{ secrets.GITHUB_TOKEN }}