name: Re-push image

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release branch or tag'
        required: true
        default: 'main'
      definition:
        description: 'Definition ID'
        required: true

jobs:
  build-and-push:
    name: Build and push images
    runs-on: ubuntu-latest
    steps:
    - name: Free more space
      id: free_space 
      run: |
        set -e
        # Ensure enough space is available for build
        sudo apt-get autoremove -y
        sudo apt-get clean -y
        sudo rm -rf /usr/share/dotnet

    - name: Checkout ref
      id: checkout_ref
      uses: actions/checkout@v2
      with:
        path: 'ref'
        ref: ${{ github.ref }}
        
    - name: Checkout release
      id: checkout_release
      uses: actions/checkout@v2
      with:
        path: 'release'
        ref: ${{ github.event.inputs.release }}

    - name: Azure CLI login
      id: az_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_ACR_CREDS }}
      
    - name: Build and push
      id: build_and_push
      run: |
        set -e

        # ACR login
        ACR_REGISTRY_NAME=$(echo ${{ secrets.REGISTRY }} | grep -oP '(.+)(?=\.azurecr\.io)')
        az acr login --name $ACR_REGISTRY_NAME

        # Setup build CLI
        cd "$GITHUB_WORKSPACE/ref"
        yarn install

        # Go to the release, symlink the build tool from ref since this is the version for the workflow
        cd "$GITHUB_WORKSPACE/release"
        rm -rf build node_modules
        ln -s "$GITHUB_WORKSPACE/ref/build" build
        ln -s "$GITHUB_WORKSPACE/ref/node_modules" node_modules

        build/vscdc push  --replace-images \
                          --release ${{ github.event.inputs.release }} \
                          --registry ${{ secrets.REGISTRY }} \
                          --registry-path ${{ secrets.REGISTRY_BASE_PATH }} \
                          --stub-registry ${{ secrets.STUB_REGISTRY }} \
                          --stub-registry-path ${{ secrets.STUB_REGISTRY_BASE_PATH }} \
                          ${{ github.event.inputs.definition }}



