name: Smoke test "python-3-miniconda" build

on: 
  workflow_dispatch:

  push:
    branches: [main, actions-test]
    paths:
      - 'containers/python-3-miniconda/**'
  pull_request:
    branches:
      - main
    paths:
      - 'containers/python-3-miniconda/**'
jobs:
  smoke-test:
    name: Smoke test
    if: "!contains(github.event.head_commit.message, 'Automated update') && !contains(github.event.head_commit.message, 'CI ignore')"
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: checkout
      uses: actions/checkout@v2

    - name: Smoke test
      id: smoke_test
      uses: ./.github/actions/smoke-test
      with:
        definition: python-3-miniconda
        image: mcr.microsoft.com/vscode/devcontainers/miniconda:dev-3
        user: vscode
